{
  "services": [
    {
      "type": "web",
      "name": "volunteer-nlp-system",
      "env": "python",
      "buildCommand": "pip install -r requirements.txt",
      "startCommand": "gunicorn volunteer_api:app --bind 0.0.0.0:$PORT"
    }
  ]
}